#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
