#!/usr/bin/env bash
#Install nginx on my 1730-web-01 server listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx start
