#!/usr/bin/env bash
#installs Nginx and sets it so that /redirect_me redirects to another page
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i '/listen \[::]:80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-301 Moved Permanently;' /etc/nginx/sites-available/default
service nginx start
