#!/usr/bin/env bash
# configures new server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
FILE="/etc/nginx/sites-available/default"
sudo sed -i "22i \\\tadd_header X-Served-By $HOSTNAME;" $FILE
service nginx start
